token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: env(eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9oa3NqNzdAZ21haWwuY29tIiwibmlja25hbWUiOiJvaGtzajc3In0.oV6aYDBxXXMSEP1nuB-rleaNj6EgYEG6zlP9DRazKfA)
  refresh-token-name: refresh-token
  access-token-name: access-token

jasypt:
  encryptor:
    password:  enc(1AjPAl/KLDrtqZfisZsNxYihuniVEBFTrX9ppRW3rVzk5uAmgTv/AfVS14fUQNfp8dYKw2cq04nHkd4aZlLNt7TW4DqiTZFPLT3AoowhFV1ovCrhRBfCCIYk6fR9Zic+ChWeNztIuHhxvp36CqsqDNQ5hQm8+/V/eCmxHHxnh41cG7L3/qfyO9N/6qtGIa57)