# 김승진
global:
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  receiver: 'slack-notifications'
  repeat_interval: 2m
receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#monitoring'
      send_resolved: true
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
