version: "3.9"

services:

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - app-tier

  discovery:
    build:
      context: ./discovery-service
    command: ./wait-for-it.sh -t 70 db:3306 -- gradle bootRun
    container_name: discovery
    ports: 
      - 8761:8761
    networks:
      - app-tier
    environment:
      - spring.config.import=optional:configserver:http://config:8888 
    tty: true

  config:
    build:
      context: ./config-service
    command: ./wait-for-it.sh -t 70 db:3306 -- gradle bootRun
    container_name: config
    ports:
      - 8888:8888
    networks:
      - app-tier
    depends_on:
      - discovery
    tty: true

  api-gateway:
    build:
      context: ./apigateway-service
    command: ./wait-for-it.sh -t 70 db:3306 -- gradle bootRun
    container_name: api-gateway
    ports: 
      - 8000:8000
    networks:
      - app-tier
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.config.import=optional:configserver:http://config:8888
      - spring.zipkin.base-url=http://zipkin:9411
    depends_on:
      - discovery
      - config
    tty: true

  guest:
    build:
      context: ./guest-service
    command: ./wait-for-it.sh -t 70 db:3306 -- gradle bootRun
    container_name: guest
    networks:
      - app-tier
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.config.import=optional:configserver:http://config:8888 
      - spring.zipkin.base-url=http://zipkin:9411    
    depends_on:
      - discovery
      - config
      - db   
    tty: true

  member:
    build:
      context: ./member-service
    command: ./wait-for-it.sh -t 70 db:3306 -- gradle bootRun
    container_name: member
    networks:
      - app-tier
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.config.import=optional:configserver:http://config:8888   
      - spring.zipkin.base-url=http://zipkin:9411  
    depends_on:
      - discovery
      - config
      - db   
    tty: true

  problem:
    build:
      context: ./problem-service
    command: ./wait-for-it.sh -t 70 db:3306 -- gradle bootRun
    container_name: problem
    networks:
      - app-tier
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.config.import=optional:configserver:http://config:8888 
      - spring.zipkin.base-url=http://zipkin:9411    
    depends_on:
      - discovery
      - config
      - db   
    tty: true

  db:
    image: mysql
    container_name: mysql-con
    ports:
      - 3307:3306
    volumes:
      - data_mysql:/mysql
    env_file:
      - .env
    networks:
      - app-tier
    tty: true

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --port 6379
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
volumes:
  data_mysql: null
