version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - build_frontend:/frontend/build
      - ./frontend/:/frontend/
      - ./frontend/node_modules/:/frontend/node_modules
    image: run
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_frontend:/var/www/frontend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    depends_on:
      - frontend
      - api-gateway
    networks:
      - app-tier
    tty: true

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - app-tier
    tty: true

  discovery:
    build:
      context: ./discovery-service
    command: gradle bootRun
    container_name: discovery
    ports: 
      - 8761:8761
    networks:
      - app-tier
    tty: true

  config:
    build:
      context: ./config-service
    command: ./wait-for-it.sh -t 15 db:3306 -- gradle bootRun
    container_name: config
    ports:
      - 8888:8888
    networks:
      - app-tier
    depends_on:
      - discovery
    tty: true

  api-gateway:
    build:
      context: ./apigateway-service
    command: ./wait-for-it.sh -t 5 config:8888 -- gradle bootRun
    container_name: api-gateway
    ports: 
      - 8000:8000
    networks:
      - app-tier
    depends_on:
      - discovery
      - config
    tty: true

  guest:
    build:
      context: ./guest-service
    command: ./wait-for-it.sh -t 10 api-gateway:8000 -- gradle bootRun
    container_name: guest
    networks:
      - app-tier   
    depends_on:
      - discovery
      - config
      - db   
    tty: true

  member:
    build:
      context: ./member-service
    command: ./wait-for-it.sh -t 10 api-gateway:8000 -- gradle bootRun
    container_name: member
    networks:
      - app-tier 
    depends_on:
      - discovery
      - config
      - db   
    tty: true

  problem:
    build:
      context: ./problem-service
    command: ./wait-for-it.sh -t 10 api-gateway:8000 -- gradle bootRun
    container_name: problem
    networks:
      - app-tier
    depends_on:
      - discovery
      - config
      - db
    tty: true

  db:
    image: mysql
    container_name: db
    ports:
      - 3307:3306
    volumes:
      - data_mysql:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-tier
    tty: true

  keycloak:
    image: jboss/keycloak
    restart: always
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    networks:
      - app-tier
    tty: true

networks:
  app-tier:
    driver: bridge

volumes:
  data_mysql: null
  build_frontend: null