global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
rule_files:
    - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'apigateway'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['api-gateway:8000']

  - job_name: 'member'
    scrape_interval: 15s
    metrics_path: '/member-service/actuator/prometheus'
    static_configs:
    - targets: ['api-gateway:8000']

  - job_name: 'problem'
    scrape_interval: 15s
    metrics_path: '/problem-service/actuator/prometheus'
    static_configs:
    - targets: ['api-gateway:8000']

  - job_name: 'guest'
    scrape_interval: 15s
    metrics_path: /guest-service/actuator/prometheus'
    static_configs:
    - targets: ['api-gateway:8000']
