server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-location: file:///${user.home}/msa-config-repo
        git:
          uri: https://github.com/ohksj77/msa-config-repo
