server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka

spring:
  application:
    name: apigateway-service

  zipkin:
    base-url: http://zipkin:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    inetutils:
      ignored-interfaces:
        - eth0
        - eth1
        - eth2
        - eth3
        - lo
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - name: GlobalFilter
          args:
            baseMessage: Algorithm Review LKC Running
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost"
            allow-credentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
            allowedHeaders: '*'
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/member-service/**
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/actuator/**
            - Method=GET,POST

        - id: guest-service
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/api/guest-service/**
        - id: guest-service
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/guest-service/actuator/**
            - Method=GET,POST

        - id: problem-service
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/api/problem-service/**
        - id: problem-service
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/problem-service/actuator/**
            - Method=GET,POST

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus
