server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka

spring:
  application:
    name: apigateway-service

  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile, email
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost/login/oauth2/code/google

  zipkin:
    base-url: http://zipkin:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost"
            allow-credentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
            allowedHeaders: '*'
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/member-service/**

        - id: guest-service
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/api/guest-service/**

        - id: problem-service
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/api/problem-service/**

management:
  endpoints:
    web:
      exposures:
        include: refresh, health, beans, httptrace
