server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka

spring:
  application:
    name: apigateway-service

  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile, email
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: http://localhost/login/oauth2/code/google

  zipkin:
    base-url: http://zipkin:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://:frontend"
            allow-credentials: true
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
            allowedHeaders: '*'
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/api/login
            - Method=POST
          filters:
            - RewritePath=/member/api/(?<segment>.*),/$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/api/reissue
            - Method=GET
          filters:
            - RewritePath=/member/api/(?<segment>.*),/$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/logout
            - Method=POST
          filters:
            - RewritePath=/member/api/(?<segment>.*),/$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/api/auth/reissue
            - Method=GET
          filters:
            - RewritePath=/member/api/(?<segment>.*),/$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/api/oauth2/authorization/*
          filters:
            - RewritePath=/member/api/(?<segment>.*),/$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/api/*/oauth2/code/*
          filters:
            - RewritePath=/member/api/(?<segment>.*),/$\{segment}

        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/api/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/member/api/(?<segment>.*),/$\{segment}

        - id: guest-service
          uri: lb://GUEST-SERVICE
          predicates:
            - Path=/guest/api/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/guest/(?<segment>.*),/$\{segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 3
                key-resolver: "#{@tokenKeyResolver}"

        - id: problem-service
          uri: lb://PROBLEM-SERVICE
          predicates:
            - Path=/problem/api/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/problem/(?<segment>.*),/$\{segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 3
                key-resolver: "#{@tokenKeyResolver}"

management:
  endpoints:
    web:
      exposures:
        include: refresh, health, beans, httptrace
